language: go

dist: xenial

go:
    - 1.11.x
    - tip

branches:
    only:
        - master
        - /^v?\d+\.\d+\.\d+(-\S*)?$/

env:
    global:
        - GO111MODULE=on
        - GOFLAGS=-mod=readonly

matrix:
    fast_finish: true
    allow_failures:
        -   go: tip

cache:
    directories:
        - bin
        - $HOME/gopath/pkg/mod

install: go mod download

script: make test
